# Generated by Django 4.2.10 on 2024-03-07 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cedula', models.CharField(max_length=10)),
                ('nombres', models.CharField(max_length=40)),
                ('apellidos', models.CharField(max_length=40)),
                ('grupo', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='ExamenTeorico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=40)),
                ('numPreguntas', models.IntegerField()),
                ('fechaRealizacion', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Practica',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=40)),
                ('dificultad', models.CharField(choices=[('Baja', 'Baja'), ('Media', 'Media'), ('Alta', 'Alta')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cedula', models.CharField(max_length=10)),
                ('apellidos', models.CharField(max_length=40)),
                ('nombres', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='ProfesoresDisenioPractica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaParticipaDisenio', models.DateTimeField()),
                ('practica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.practica')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.profesor')),
            ],
        ),
        migrations.CreateModel(
            name='PracticaAlumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaRealizada', models.DateTimeField()),
                ('nota', models.IntegerField()),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.alumno')),
                ('practica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.practica')),
            ],
        ),
        migrations.CreateModel(
            name='ExamenTeoricoAlumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.FloatField()),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.alumno')),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.examenteorico')),
            ],
        ),
        migrations.AddField(
            model_name='examenteorico',
            name='profesorDisenio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.profesor'),
        ),
    ]
